import requests
import json
import base64
import os

def test_screen_capture():
    """
    Test the screen capture endpoint.
    """
    url = "http://localhost:5001/api/v1/generate-image"
    
    html_content = """
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; font-family: sans-serif;">
        <div style="text-align: center;">
            <h1 style="font-size: 4rem; margin-bottom: 20px;">Hello, Screen Capture!</h1>
            <p style="font-size: 1.5rem;">Generated by Playwright on Python Flask</p>
            <i class="fas fa-camera" style="font-size: 3rem; margin-top: 20px;"></i>
        </div>
    </div>
    """
    
    payload = {
        "html": html_content,
        "css": "h1 { text-shadow: 2px 2px 4px rgba(0,0,0,0.5); }",
        "width": 1280,
        "height": 720
    }
    
    headers = {
        "Content-Type": "application/json"
        # Add "X-API-Key": "your-key" if authentication is enabled and strict
    }
    
    print(f"Sending request to {url}...")
    try:
        response = requests.post(url, json=payload, headers=headers)
        
        if response.status_code == 200:
            print("Success! Image received.")
            output_file = "test_capture_result.png"
            with open(output_file, "wb") as f:
                f.write(response.content)
            print(f"Saved screenshot to {output_file}")
            print(f"Image size: {len(response.content)} bytes")
        else:
            print(f"Error: {response.status_code}")
            print(response.text)
            
    except requests.exceptions.ConnectionError:
        print("Failed to connect. Is the server running? (Make sure port 5001 is mapped)")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    test_screen_capture()
